# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_of_payment', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.CharField(blank=True, choices=[('M', 'Monthly_Fee'), ('A', 'Admission_Fee')], default='M', max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Playgroup', 'Playgroup'), ('Nursery', 'Nursery'), ('PREP', 'PREP'), ('1st Grade', '1st Grade'), ('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade'), ('4th Grade', '4th Grade')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('mobile_code', models.CharField(choices=[(b'0300', b'0300'), (b'0301', b'0301'), (b'0302', b'0302'), (b'0303', b'0303'), (b'0304', b'0304'), (b'0305', b'0305'), (b'0306', b'0306'), (b'0307', b'0307'), (b'0308', b'0308'), (b'0309', b'0309'), (b'0310', b'0310'), (b'0311', b'0311'), (b'0312', b'0312'), (b'0313', b'0313'), (b'0314', b'0314'), (b'0315', b'0315'), (b'0320', b'0320'), (b'0321', b'0321'), (b'0322', b'0322'), (b'0323', b'0323'), (b'0324', b'0324'), (b'0331', b'0331'), (b'0332', b'0332'), (b'0333', b'0333'), (b'0334', b'0334'), (b'0335', b'0335'), (b'0336', b'0336'), (b'0337', b'0337'), (b'0340', b'0340'), (b'0341', b'0341'), (b'0342', b'0342'), (b'0343', b'0343'), (b'0344', b'0344'), (b'0345', b'0345'), (b'0346', b'0346'), (b'0347', b'0347'), (b'0348', b'0348'), (b'0349', b'0349')], default='0300', max_length=4)),
                ('seven_digit_phone', models.CharField(blank=True, max_length=7, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(default='1/1/2000')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.Level')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeCategory'),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
    ]
