# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feecategory',
            old_name='amount',
            new_name='fee_amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='month',
            field=models.CharField(choices=[(b'1', b'January'), (b'2', b'February'), (b'3', b'March'), (b'4', b'April'), (b'5', b'May'), (b'6', b'June'), (b'7', b'July'), (b'8', b'August'), (b'9', b'September'), (b'10', b'October'), (b'11', b'November'), (b'12', b'December')], default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='fee_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together=set([('student', 'month')]),
        ),
    ]
